format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Customize the prompt symbol
[character]
success_symbol = "[→] (bold green)"

# Disable the package module
[package]
disabled = true

# Customize the directory module
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Customize the git branch module
[git_branch]
symbol = "🌿 "

# Customize the git status module
[git_status]
style = "bold red"

# Python module configuration
[python]
format = "via [🐍 $version](bold blue) "
# Show the Python version if a .py file is present
detect_extensions = ["py"]
# Show the Python version if a requirements.txt or pyproject.toml file is present
detect_files = ["requirements.txt", "pyproject.toml"]
# Show the Python version if a .venv directory is present
detect_folders = [".venv"]

# Dart module configuration
[dart]
format = "via [🎯 $version](bold cyan) "
# Show the Dart version if a .dart file is present
detect_extensions = ["dart"]
# Show the Dart version if a pubspec.yaml or pubspec.lock file is present
detect_files = ["pubspec.yaml", "pubspec.lock"]
# Show the Dart version if a .dart_tool directory is present
detect_folders = [".dart_tool"]

# Rust module configuration
[rust]
format = "via [🦀 $version](bold red) "
# Show the Rust version if a .rs file is present
detect_extensions = ["rs"]
# Show the Rust version if a Cargo.toml file is present
detect_files = ["Cargo.toml"]
# Show the Rust version if a target directory is present
detect_folders = ["target"]

# Customize the nodejs module
[nodejs]
format = "via [⬢ $version](bold blue) "

# Customize the time module
[time]
format = "🕒 [$time]($style) "
style = "bold yellow"
disabled = false
